name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - development

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
          # Defaults to the user or organization that owns the workflow file
          scope: "@yafetch"

      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap

      - name: Run tests
        run: npx lerna run test-ci
